ALTER TABLE cafe ADD FULLTEXT INDEX cafe_name_idx (name) WITH PARSER NGRAM;

ALTER TABLE cafe ADD FULLTEXT INDEX address_idx (address) WITH PARSER NGRAM;

ALTER TABLE menu ADD FULLTEXT INDEX menu_name_idx (name) WITH PARSER NGRAM;