version: "3"
services:
  web:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/archive/${DOMAIN?"DOMAIN should not empty"}:/etc/ssl:ro
      - ~/public:/usr/share/nginx/html:ro
      - ~/images:/images:ro

  mysql:
    platform: linux/arm64/v8
    image: library/mysql:8.0.33
    restart: unless-stopped
    ports:
      - 20000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yozm-cafe
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
